/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println("=== Debug Test ===")
    println(App().greeting)
    
    println("\n=== Testing Calculator Interface ===")
    debugCalculator()
}

fun debugCalculator() {
    println("Calculator tests (would use native library):")
    println("- Interface: ICalculator (abstract class with pure virtual methods)")
    println("- Implementation: Calculator concrete class")
    println("- Methods: add, subtract, multiply")
    
    // Simulating what would happen with JNI bridge
    println("\nSimulated calculations:")
    println("10 + 5 = ${simpleAdd(10, 5)}")
    println("10 - 3 = ${simpleSubtract(10, 3)}")
    println("10 * 4 = ${simpleMultiply(10, 4)}")
}

fun simpleAdd(a: Int, b: Int) = a + b
fun simpleSubtract(a: Int, b: Int) = a - b
fun simpleMultiply(a: Int, b: Int) = a * b

