/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// C++ native library build task
tasks.register("buildNative") {
    group = "build"
    description = "Builds the C++ native library using CMake"
    
    doLast {
        val buildDir = File(layout.buildDirectory.get().asFile, "native")
        val sourceDir = rootProject.projectDir.absolutePath
        buildDir.mkdirs()
        
        try {
            // Configure CMake
            ProcessBuilder("cmake", "-DCMAKE_BUILD_TYPE=Release", sourceDir)
                .directory(buildDir)
                .inheritIO()
                .start()
                .waitFor()
            
            // Build with CMake
            ProcessBuilder("cmake", "--build", ".")
                .directory(buildDir)
                .inheritIO()
                .start()
                .waitFor()
            
            println("C++ native library built successfully")
        } catch (e: Exception) {
            println("Warning: CMake build failed. Is CMake installed? Error: ${e.message}")
        }
    }
}

// C++ native library debug build task
tasks.register("buildNativeDebug") {
    group = "build"
    description = "Builds the C++ native library using CMake with debug symbols"
    
    doLast {
        val buildDir = File(layout.buildDirectory.get().asFile, "native_debug")
        val sourceDir = rootProject.projectDir.absolutePath
        buildDir.mkdirs()
        
        try {
            // Configure CMake with Debug configuration
            ProcessBuilder("cmake", "-DCMAKE_BUILD_TYPE=Debug", sourceDir)
                .directory(buildDir)
                .inheritIO()
                .start()
                .waitFor()
            
            // Build with CMake
            ProcessBuilder("cmake", "--build", ".", "--config", "Debug")
                .directory(buildDir)
                .inheritIO()
                .start()
                .waitFor()
            
            println("C++ native library built successfully in Debug mode")
        } catch (e: Exception) {
            println("Warning: CMake debug build failed. Is CMake installed? Error: ${e.message}")
        }
    }
}

tasks.named("build") {
    dependsOn("buildNative")
}

